### ISSUE TITLE
New to Dataset

### ISSUE THREAD

**Issue by ayushidalmia** [gousiosg/ghtorrent.org#19]
Hi,

I am new to this dataset. I was trying to understand the underlying structure with the details of each field in the mongodb. However, I could not come across any particular documentation for the same.

I browsed the Github API documentation but it did not help me much. Taking an example entry and opening the url helps me more or less figure out more or less, however an official documentation would have helped.

Thanks

**Comment by gousiosg** [comment]
Hi, thanks for the comment. GHTorrent does not do any processing for the data that is being stored in MongoDB. It just stores whatever GitHub produces. Some of the data is self descriptive, some is not. 

I agree with you that a more detailed description of the data being returned by Github would be beneficial. If during your research you manage to come up with a documentation scheme for even parts of the data, please submit a pull request and I will work with you to make it mergable.

**Comment by ayushidalmia** [comment]
Thanks! 

If I can figure out the fields I would submit a pull request.
