### ISSUE TITLE
MySQL Dump as Torrent

### ISSUE THREAD

**Issue by DerekTBrown** [gousiosg/ghtorrent.org#24]
As the size increases, it may be worthwhile to consider hosting the MySQL dump as a torrent file, and include ghtorrent.org as an HTTP Seed for the file.  This would certainly increase the download speed for users, and would reduce the load on the server.

Thanks for all your great work!

Derek

**Comment by gousiosg** [comment]
Thanks for the suggestion. The project used to offer torrent files long ago; however

1. Most users preferred HTTP downloads
2. No user continued to share after download. This essentially meant that our server incurred the same bandwidth load.
3. We moved to a different server that is behind a corporate firewall and opening additional ports is a complicated process
4. The administrative cost of running an extra service is non-neligible

So we decided to stick with plain old HTTP.
